---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-app-pull-request
  annotations:
    # The event we are targeting (ie: pull_request, push)
    pipelinesascode.tekton.dev/on-event: "[pull_request]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the git-clone task from hub, we are able to reference it with taskRef
    pipelinesascode.tekton.dev/task: "[git-clone]"

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec: 
    params:
    - name: echo-value
      description: The value to echo out
      default: code
    tasks:
      - name: fetch
        taskSpec:
          params:
          - name: echo-value-for-task
            description: The value to echo out
            default: this is not the param you're looking for
          steps:
            - name: echo
              image: ubuntu
              command:
                - echo
              args:
                - "$(inputs.params.echo-value-for-task)"
        params:
          - name: echo-value-for-task
            value: "fetching $(params.echo-value)"
      - name: build
        taskSpec:
          params:
          - name: echo-value-for-task
            description: The value to echo out
            default: this is not the param you're looking for
          steps:
            - name: echo
              image: ubuntu
              command:
                - echo
              args:
                - "$(inputs.params.echo-value-for-task)"
        params:
          - name: echo-value-for-task
            value: "building $(params.echo-value)"
      - name: deploy
        taskSpec:
          params:
          - name: echo-value-for-task
            description: The value to echo out
            default: this is not the param you're looking for
          steps:
            - name: echo
              image: ubuntu
              command:
                - echo
              args:
                - "$(inputs.params.echo-value-for-task)"
        params:
          - name: echo-value-for-task
            value: "deploying $(params.echo-value)"

